### Start from python slim dockerfile
FROM python:3.7-alpine

### install app requirements (Copy the file and install)
COPY requirements.txt /
RUN pip install -r /requirements.txt

### Copy app folder to /app
COPY src/ /app

### Set /app to be the main workdir
WORKDIR /app

### Expose gunicorn default port
EXPOSE 8000

### Set the command to execute to be gunicorn
CMD ["gunicorn", "-w 4", "--bind=0.0.0.0", "main:app"]
